### PR TITLE
Update to Grails 3

### PR DESCRIPTION
**Pull request by bobbywarner**
Not sure if you are still maintaining this plugin or not and if you have any plans on releasing a Grails 3 version.  If not, I'm happy to take over ownership of the plugin and release the Grails 3 version to Bintray.  Please let me know.

### CODE REVIEW

**Comment by aalmiray** [comment]
As the original author of the plugin I say: yes, we'd love to see an upgrade to Grails 3. I'm afraid I'm been out of touch with Grails for a while. @berngp is certainly quite busy too. So here's 1 out of 2 votes to follow Bobby's proposal to take over :wink:

**Comment by berngp** [comment]
I vote for it too so 2 out of 2 votes :).

**Comment by berngp** [comment]
@bobbywarner I can't transfer you the ownership since you already have a grails-rest project. Let me know what you want to do.

**Comment by bobbywarner** [comment]
@berngp Ok, great!  Yea, I'll take over ownership of it.  Do you want to merge the pull request and then I'll delete my `grails-rest` repo so you can transfer ownership?  Please let me know.

**Comment by berngp** [comment]
@bobbywarner let me know when you mv or rm your repo and I'll transfer the ownership of the project.

**Comment by bobbywarner** [comment]
@berngp I have deleted my fork repo.  Please transfer anytime.  Thanks!

**Comment by berngp** [comment]
@bobbywarner done, thanks for stepping up.

**Pull request merged**
